camel:
  springboot:
    main-run-controller: true

logging:
  level:
    org:
      springframework: INFO
      hibernate:
        sql: INFO
    br:
      com:
        bnck: INFO


spring:
  activemq:
    broker-url: "tcp://localhost:61616"
    packages:
      trust-all: true