camel:
  springboot:
    main-run-controller: true

logging:
  level:
    org:
      springframework: INFO
      hibernate:
        sql: INFO
    br:
      com:
        bnck: INFO


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: developer2022
#    url: jdbc:mysql://localhost:3306/myDb?